# We want to use the KVM-based system, so require sudo
sudo: required
services:
  - docker

before_install:
  - git clone https://github.com/mozilla/discourse-mozilla-travis.git

install: true

before_script:
  - source discourse-mozilla-travis/before_script.sh

script:
  - discourse-mozilla-travis/script.sh
