plugins:
  auto_email_in_enabled:
    default: false
  auto_email_in_divider:
    default: '+'
    shadowed_by_global: true
  auto_email_in_domain:
    default: 'example.com'
    shadowed_by_global: true
